- conf/application.conf
- conf/prod.routes
https://jira.tools.tax.service.gov.uk/browse/HIPP-183
Base path is now /api-hub to match that configured for the admin frontend proxy
> HIPP-183: Base path is now /api-hub

- .gitignore
- app/views/IndexView.scala.html
It's not completely right aligned but we aren't sure this is how we will do this, nor are we too bothered for Technical MVP.
> HIPP-199: Sign In Link that goes nowhere

- app/controllers/ApplicationNameController.scala
- app/controllers/IndexController.scala
- app/forms/ApplicationNameFormProvider.scala
- app/navigation/Navigator.scala
- app/pages/ApplicationNamePage.scala
- app/viewmodels/checkAnswers/ApplicationNameSummary.scala
- app/views/ApplicationNameView.scala.html
- app/views/IndexView.scala.html
- conf/app.routes
- conf/application.conf
- conf/messages.en
- project/build.properties
- test-utils/generators/UserAnswersEntryGenerators.scala
- test-utils/generators/UserAnswersGenerator.scala
- test/controllers/ApplicationNameControllerSpec.scala
- test/controllers/IndexControllerSpec.scala
- test/forms/ApplicationNameFormProviderSpec.scala
- test/navigation/NavigatorSpec.scala
- test/pages/ApplicationNamePageSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-39
Use scaffold to create page for Application Name.
> HIPP-39: Add Application Name page

- app/controllers/actions/IdentifierAction.scala
- test/controllers/actions/AuthActionSpec.scala
Swap from using auth-login-stub to authenticating with Stride.
> HIPP-39: Stride Login

- app/controllers/CheckYourAnswersController.scala
- test/controllers/CheckYourAnswersControllerSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-200
> HIPP-200: Add Application Name to Check Your Answers

- app/connectors/ApplicationsConnector.scala
- app/controllers/CreateApplicationController.scala
- app/models/Application.scala
- app/services/ApiHubService.scala
- app/services/ApplicationsService.scala
- conf/app.routes
- conf/application.conf
- conf/messages.en
- it/connectors/ApplicationsConnectorSpec.scala
- project/AppDependencies.scala
- test/controllers/CreateApplicationControllerSpec.scala
- test/services/ApiHubServiceSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-197
> HIPP-197: Register an application from the Check Your Answers page

- conf/app.routes
https://jira.tools.tax.service.gov.uk/browse/HIPP-231
Standardise URLs to lower kebab-case
> HIPP-231: Standardise URLs

- app/connectors/ApplicationsConnector.scala
- app/services/ApiHubService.scala
- it/connectors/ApplicationsConnectorSpec.scala
- test/services/ApiHubServiceSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-38
This PR is just for the connector to the backend. I will add the controller and view changes next.
> HIPP-38: View all applications

- app/controllers/ApplicationDetailsController.scala
- app/views/ApplicationDetailsView.scala.html
- app/views/CreateApplicationSuccessView.scala.html
- conf/app.routes
- conf/messages.en
- project/plugins.sbt
- test/controllers/ApplicationDetailsControllerSpec.scala
- test/controllers/CreateApplicationSuccessControllerSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-35
> HIPP-35: Create Applications Details page

- app/controllers/RequestScopeSuccessController.scala
- app/views/RequestScopeSuccessView.scala.html
- conf/app.routes
- conf/messages.en
- test/controllers/RequestScopeSuccessControllerSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-278
> HIPP-278: Build frontend - Scope successfully requested

- app/views/templates/Layout.scala.html
- conf/messages.en
https://jira.tools.tax.service.gov.uk/browse/HIPP-318
> HIPP-318: Add links to top of every page

- app/controllers/actions/IdentifierAction.scala
- conf/application.conf
- project/AppDependencies.scala
- project/plugins.sbt
- test/controllers/actions/AuthActionSpec.scala
Part one - User must be authenticated as any Ldap user.
> Hipp 315 ldap authentication

- app/testonly/Permission.scala
- app/testonly/TestOnlyAddTokenRequest.scala
- app/testonly/TestOnlyInternalAuthConnector.scala
- app/testonly/TestOnlySignInController.scala
- app/views/TestOnlySignIn.scala.html
- build.sbt
- conf/application.conf
- conf/messages.en
- conf/testOnlyDoNotUseInAppConf.routes
https://jira.tools.tax.service.gov.uk/browse/HIPP-233
> HIPP-233: LDAP stub

- app/controllers/actions/IdentifierAction.scala
- app/models/user/UserModel.scala
- app/testonly/Retrievals.scala
- app/testonly/TestOnlySignInController.scala
- app/views/templates/Layout.scala.html
- test/controllers/actions/AuthActionSpec.scala
- test/controllers/actions/DataRetrievalActionSpec.scala
- test/controllers/actions/FakeIdentifierAction.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-311
> HIPP-311: Retrieve and use approver permissions in frontend 

- app/connectors/ApplicationsConnector.scala
- app/controllers/PendingApprovalsController.scala
- app/services/ApiHubService.scala
- app/views/PendingApprovalsView.scala.html
- app/views/templates/Layout.scala.html
- conf/app.routes
- conf/messages.en
- it/connectors/ApplicationsConnectorSpec.scala
- test/controllers/PendingApprovalsControllerSpec.scala
- test/services/ApiHubServiceSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-264
> HIPP-264: Pending production approvals page

- app/controllers/PendingApprovalsController.scala
- app/controllers/UnauthorisedController.scala
- app/controllers/actions/AuthorisedApproverAction.scala
- conf/messages.en
- test/base/SpecBase.scala
- test/controllers/PendingApprovalsControllerSpec.scala
- test/controllers/UnauthorisedControllerSpec.scala
- test/controllers/actions/AuthorisedApproverActionSpec.scala
- test/controllers/actions/FakeApprover.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-359
> HIPP-359: Approver-only pages

- app/views/ApplicationDetailsView.scala.html
- conf/messages.en
https://jira.tools.tax.service.gov.uk/browse/HIPP-228
> HIPP-228: Display scopes

- app/controllers/ScopeApprovedController.scala
- app/views/ScopeApprovedView.scala.html
- conf/app.routes
- conf/messages.en
- test/controllers/ScopeApprovedControllerSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-244
> HIPP-244: Scopes granted success page

- app/controllers/ExperimentalStrideLoginController.scala
> HIPP-360: Test Stride login in Prod

- app/controllers/QuestionAddTeamMembersController.scala
- app/navigation/Navigator.scala
- app/views/QuestionAddTeamMembersView.scala.html
- conf/messages.en
- test/controllers/QuestionAddTeamMembersControllerSpec.scala
- test/navigation/NavigatorSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-34
> HIPP-34: Do you want to add a team member?

- app/controllers/AddTeamMemberDetailsController.scala
- app/forms/AddTeamMemberDetailsFormProvider.scala
- app/navigation/Navigator.scala
- app/pages/TeamMembersPage.scala
- app/viewmodels/checkAnswers/AddTeamMemberDetailsSummary.scala
- app/views/AddTeamMemberDetailsView.scala.html
- conf/app.routes
- conf/messages.en
- test-utils/generators/ModelGenerators.scala
- test-utils/generators/PageGenerators.scala
- test-utils/generators/UserAnswersEntryGenerators.scala
- test-utils/generators/UserAnswersGenerator.scala
- test/controllers/AddTeamMemberDetailsControllerSpec.scala
- test/forms/AddTeamMemberDetailsFormProviderSpec.scala
- test/forms/behaviours/FieldBehaviours.scala
- test/navigation/NavigatorSpec.scala
- test/pages/TeamMembersPageSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-367
> HIPP-367: Add a team member

- app/controllers/RegisterApplicationController.scala
- app/forms/AddTeamMemberDetailsFormProvider.scala
- app/models/application/Application.scala
- app/models/application/NewApplication.scala
- it/connectors/ApplicationsConnectorSpec.scala
- test/controllers/AddScopeControllerSpec.scala
- test/controllers/ApplicationDetailsControllerSpec.scala
- test/controllers/IndexControllerSpec.scala
- test/controllers/PendingApprovalsControllerSpec.scala
- test/controllers/RegisterApplicationControllerSpec.scala
- test/controllers/RegisterApplicationSuccessControllerSpec.scala
- test/controllers/RequestScopeSuccessControllerSpec.scala
- test/services/ApiHubServiceSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-405
> HIPP-405: Send team members when a user clicks "Register application"

- app/navigation/Navigator.scala
- app/viewmodels/checkAnswers/ConfirmAddTeamMember.scala
- test/controllers/ConfirmAddTeamMemberControllerSpec.scala
- test/navigation/NavigatorSpec.scala
- test/viewmodels/checkAnswers/ConfirmAddTeamMemberSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-111
> HIPP-111: Change team member details - Team members confirmation page

- app/controllers/ExperimentalLdapAuth.scala
- app/controllers/ExperimentalStrideAuth.scala
- app/controllers/ExperimentalStrideLoginController.scala
- app/models/user/UserModel.scala
- conf/app.routes
https://jira.tools.tax.service.gov.uk/browse/HIPP-447
> HIPP-447: Sign-in flow

- app/assets/stylesheets/application.scss
- app/controllers/ExperimentalLdapAuth.scala
- app/controllers/actions/Authenticator.scala
- app/controllers/actions/IdentifierAction.scala
- app/controllers/actions/LdapAuthenticator.scala
- app/controllers/actions/StrideAuthenticator.scala
- app/controllers/actions/UserAuthResult.scala
- app/controllers/auth/SignInController.scala
- app/testonly/TestOnlySignInController.scala
- app/views/auth/SignInView.scala.html
- conf/app.routes
- conf/messages.en
- test/controllers/actions/AuthActionSpec.scala
- test/controllers/actions/LdapAuthenticatorSpec.scala
- test/controllers/auth/SignInControllerSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-450
> HIPP-450: Sign in as an LDAP user

- app/assets/stylesheets/application.css
- app/views/ConfirmAddTeamMemberView.scala.html
- app/views/RegisterApplicationSuccessView.scala.html
- app/views/RequestScopeSuccessView.scala.html
- app/views/templates/ApiHubHeader.scala.html
- app/views/templates/Layout.scala.html
- project/plugins.sbt
https://jira.tools.tax.service.gov.uk/browse/HIPP-454
Also removed Sassify as we don't use it and it does not work under Java 11 with Apple M1 chips.
> HIPP-454: Build header

- app/views/ApplicationDetailsView.scala.html
https://jira.tools.tax.service.gov.uk/browse/HIPP-508
> HIPP-508: Display client ID and secret on frontend

- app/connectors/ApplicationsConnector.scala
- app/controllers/GeneratePrimarySecretSuccessController.scala
- app/models/Lens.scala
- app/models/application/ApplicationLenses.scala
- app/models/application/Secret.scala
- app/services/ApiHubService.scala
- app/viewmodels/GeneratePrimarySecretSuccessViewModel.scala
- app/views/ApplicationDetailsView.scala.html
- app/views/GeneratePrimarySecretSuccessView.scala.html
- conf/app.routes
- conf/messages.en
- it/connectors/ApplicationsConnectorSpec.scala
- test/controllers/GeneratePrimarySecretSuccessControllerSpec.scala
- test/models/application/ApplicationLensesSpec.scala
- test/services/ApiHubServiceSpec.scala
- test/viewmodels/GeneratePrimarySecretSuccessViewModelSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-487
> HIPP-487: Frontend success page

- app/controllers/actions/ApplicationAuthAction.scala
- app/controllers/actions/LdapAuthenticator.scala
- app/controllers/actions/StrideAuthenticator.scala
- app/models/user/UserModel.scala
- app/testonly/Retrievals.scala
- app/testonly/TestOnlySignInController.scala
- test/controllers/AddScopeControllerSpec.scala
- test/controllers/ApplicationDetailsControllerSpec.scala
- test/controllers/GeneratePrimarySecretSuccessControllerSpec.scala
- test/controllers/RegisterApplicationSuccessControllerSpec.scala
- test/controllers/RequestScopeSuccessControllerSpec.scala
- test/controllers/actions/ApplicationAuthActionSpec.scala
- test/controllers/actions/AuthActionSpec.scala
- test/controllers/actions/FakeAdministrator.scala
- test/controllers/actions/FakeApprover.scala
- test/controllers/actions/LdapAuthenticatorSpec.scala
- test/controllers/actions/StrideAuthenticatorSpec.scala
- test/utils/TestHelpers.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-601
> HIPP-601: Allow Administrator to manage any application

- app/connectors/ApplicationsConnector.scala
- app/controllers/ApplicationDetailsController.scala
- app/services/ApiHubService.scala
- app/views/ApplicationDetailsView.scala.html
- conf/app.routes
- conf/messages.en
- it/connectors/ApplicationsConnectorSpec.scala
- test/controllers/ApplicationDetailsControllerSpec.scala
- test/services/ApiHubServiceSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-605
> HIPP-605: Create frontend “Delete Application” button

- app/controllers/ProductionCredentialsChecklistController.scala
- app/forms/ProductionCredentialsChecklistFormProvider.scala
- app/models/ProductionCredentialsChecklist.scala
- app/viewmodels/govuk/CheckboxFluency.scala
- app/views/ApplicationDetailsView.scala.html
- app/views/ProductionCredentialsChecklistView.scala.html
- conf/app.routes
- conf/messages.en
- test-utils/generators/ModelGenerators.scala
- test/controllers/ProductionCredentialsChecklistControllerSpec.scala
- test/forms/ProductionCredentialsChecklistFormProviderSpec.scala
- test/models/ProductionCredentialsChecklistSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-483
> HIPP-483: Production credentials checklist page

- app/connectors/ApplicationsConnector.scala
- app/controllers/ApplicationDetailsController.scala
- app/controllers/ApproveScopeController.scala
- app/controllers/actions/ApplicationAuthAction.scala
- app/services/ApiHubService.scala
- it/connectors/ApplicationsConnectorSpec.scala
- test/controllers/AddScopeControllerSpec.scala
- test/controllers/ApplicationDetailsControllerSpec.scala
- test/controllers/ApproveScopeControllerSpec.scala
- test/controllers/GeneratePrimarySecretSuccessControllerSpec.scala
- test/controllers/ProductionCredentialsChecklistControllerSpec.scala
- test/controllers/RegisterApplicationSuccessControllerSpec.scala
- test/controllers/RequestScopeSuccessControllerSpec.scala
- test/controllers/TestConnectivityControllerSpec.scala
- test/controllers/actions/ApplicationAuthActionSpec.scala
- test/services/ApiHubServiceSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-635
> HIPP-635: Change application details page to call enrichment endpoint

- app/views/TestOnlySignIn.scala.html
- app/views/templates/Layout.scala.html
- conf/application.conf
- test/resources/application.conf
https://jira.tools.tax.service.gov.uk/browse/HIPP-636
> HIPP-636: Update CSP configuration in api-hub-frontend

- conf/application.conf
https://jira.tools.tax.service.gov.uk/browse/HIPP-363
> HIPP-363: Add the accessibility statement to the API Hub

- app/config/CryptoProvider.scala
- app/config/Module.scala
- app/models/UserAnswers.scala
- app/repositories/SessionRepository.scala
- conf/application.conf
- it/repositories/SessionRepositorySpec.scala
- project/AppDependencies.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-741
> HIPP-741: Encrypt emails Mongo in api-hub-frontend

- app/controllers/ApproveScopeController.scala
- test/controllers/ApproveScopeControllerSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-718
> HIPP-718: Approve scope journey missing success page

- app/config/InternalAuthTokenInitialiser.scala
- app/config/Module.scala
- app/connectors/IntegrationCatalogueConnector.scala
- app/controllers/ApiDetailsController.scala
- app/controllers/actions/OptionalIdentifierAction.scala
- app/models/api/ApiDetail.scala
- app/models/api/Endpoint.scala
- app/models/api/EndpointMethod.scala
- app/models/api/IntegrationId.scala
- app/models/requests/OptionalIdentifierRequest.scala
- app/services/ApiHubService.scala
- app/views/ApiDetailsView.scala.html
- conf/app.routes
- conf/application.conf
- conf/messages.en
- it/config/InternalAuthTokenInitialiserSpec.scala
- it/connectors/IntegrationCatalogueConnectorSpec.scala
- test-utils/generators/ApiDetailGenerators.scala
- test/base/OptionallyAuthenticatedSpecBase.scala
- test/controllers/ApiDetailsControllerSpec.scala
- test/controllers/actions/FakeOptionalIdentifierAction.scala
- test/controllers/actions/OptionalIdentifierActionSpec.scala
- test/controllers/actions/OptionalUserProvider.scala
- test/services/ApiHubServiceSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-716
> HIPP-716: Create basic API Details Page

- app/config/Module.scala
- app/controllers/ApiDetailsController.scala
- app/controllers/actions/AddAnApiDataRetrievalAction.scala
- app/repositories/AddAnApiSessionRepository.scala
- app/repositories/UserAnswersRepository.scala
- it/repositories/AddAnApiSessionRepositorySpec.scala
- it/repositories/UserAnswersRepositoryBehaviours.scala
- test/base/SpecBase.scala
- test/controllers/actions/AddAnApiDataRetrievalActionSpec.scala
- test/controllers/actions/FakeAddAnApiDataRetrievalAction.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-761
> HIPP-761: Split session repository for new Add an API journey

- app/controllers/AddAnApiStartController.scala
- app/controllers/ApiDetailsController.scala
- app/pages/AddAnApiApiIdPage.scala
- app/views/ApiDetailsView.scala.html
- conf/app.routes
- conf/messages.en
- test/controllers/AddAnApiStartControllerSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-762
> HIPP-762: Add to application button

- app/assets/stylesheets/application.css
- app/connectors/ApplicationsConnector.scala
- app/controllers/AddAnApiSelectApplicationController.scala
- app/controllers/HipApisController.scala
- app/forms/AddAnApiSelectApplicationFormProvider.scala
- app/models/api/ApiDetailLenses.scala
- app/models/application/ApplicationLenses.scala
- app/navigation/Navigator.scala
- app/pages/AddAnApiSelectApplicationPage.scala
- app/services/ApiHubService.scala
- app/views/AddAnApiSelectApplicationView.scala.html
- app/views/templates/ApiHubHeader.scala.html
- conf/app.routes
- conf/messages.en
- it/connectors/ApplicationsConnectorSpec.scala
- it/connectors/IntegrationCatalogueConnectorSpec.scala
- test/controllers/AddAnApiSelectApplicationControllerSpec.scala
- test/controllers/IndexControllerSpec.scala
- test/forms/AddAnApiSelectApplicationFormProviderSpec.scala
- test/models/api/ApiDetailLensesSpec.scala
- test/models/application/ApplicationLensesSpec.scala
- test/pages/AddAnApiApiIdPageSpec.scala
- test/pages/AddAnApiSelectApplicationPageSpec.scala
- test/services/ApiHubServiceSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-765
> HIPP-765: Select Application - frontend

- app/connectors/ApplicationsConnector.scala
- app/controllers/AddAnApiCheckYourAnswersController.scala
- app/controllers/AddAnApiCompleteController.scala
- app/navigation/Navigator.scala
- app/services/ApiHubService.scala
- app/views/AddAnApiCheckYourAnswersView.scala.html
- app/views/ApiPolicyConditionsDeclarationPageView.scala.html
- conf/app.routes
- it/connectors/ApplicationsConnectorSpec.scala
- test/controllers/AddAnApiCheckYourAnswersControllerSpec.scala
- test/controllers/AddAnApiCompleteControllerSpec.scala
- test/services/ApiHubServiceSpec.scala
- test/viewmodels/checkAnswers/AddAnApiSelectEndpointsSummarySpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-768
> HIPP-768: Add an API - Complete the Journey - frontend

- app/controllers/AddAnApiCompleteController.scala
- app/navigation/Navigator.scala
- test/controllers/AddAnApiCompleteControllerSpec.scala
- test/controllers/AddAnApiSuccessControllerSpec.scala
- test/navigation/NavigatorSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-754
> HIPP-754: Navigation

- app/views/ApiDetailsView.scala.html
Fix missing Add to an application button on the API Details page
> HIPP-652: Fix missing Add to an application button

- app/controllers/application/ApplicationApisController.scala
- app/viewmodels/application/ApplicationNavItems.scala
- app/views/application/ApplicationApisView.scala.html
- conf/application.routes
- conf/messages.en
- test/controllers/application/ApplicationApisControllerSpec.scala
- test/viewmodels/application/ApplicationNavItemsSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-782
> HIPP-782: Manage application APIs - No APIs

- app/controllers/application/ApplicationDetailsController.scala
- test/controllers/application/ApplicationDetailsControllerSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-730
Team members list was not sorted correctly.
> HIPP-730: Sort team members

- app/assets/stylesheets/application.css
- app/views/ApiDetailsView.scala.html
- conf/application.conf
- conf/messages.en
- test-utils/generators/ApiDetailGenerators.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-392
> HIPP-392: Refactor API Details page

- app/controllers/ProductionCredentialsChecklistController.scala
- app/models/application/ApplicationLenses.scala
- app/models/application/Credential.scala
- test/controllers/ProductionCredentialsChecklistControllerSpec.scala
- test/controllers/actions/FakeApplication.scala
- test/models/application/ApplicationLensesSpec.scala
- test/viewmodels/GeneratePrimarySecretSuccessViewModelSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-830
> HIPP-830: Support multiple credentials - frontend

- app/controllers/application/ApplicationApisController.scala
- app/views/application/ApplicationApisView.scala.html
- app/views/application/ApplicationNav.scala.html
- conf/messages.en
- test/controllers/application/ApplicationApisControllerSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-731
> HIPP-731: Manage application APIs - API added

- app/controllers/actions/AuthorisedPrivilegedUserAction.scala
- app/controllers/actions/LdapAuthenticator.scala
- app/controllers/actions/StrideAuthenticator.scala
- app/controllers/application/AddCredentialController.scala
- app/models/user/UserModel.scala
- app/testonly/Retrievals.scala
- app/testonly/TestOnlySignInController.scala
- app/views/application/EnvironmentAndCredentialsView.scala.html
- conf/messages.en
- project/plugins.sbt
- test/controllers/IndexControllerSpec.scala
- test/controllers/actions/AuthActionSpec.scala
- test/controllers/actions/AuthorisedPrivilegedUserActionSpec.scala
- test/controllers/actions/FakeAdministrator.scala
- test/controllers/actions/FakeApprover.scala
- test/controllers/actions/FakePrivilegedUser.scala
- test/controllers/actions/LdapAuthenticatorSpec.scala
- test/controllers/actions/OptionalIdentifierActionSpec.scala
- test/controllers/actions/StrideAuthenticatorSpec.scala
- test/controllers/application/AddCredentialControllerSpec.scala
- test/utils/TestHelpers.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-803
> HIPP-803: Restrict adding prod credentials to privileged users

- app/connectors/ApplicationsConnector.scala
- app/controllers/admin/AccessRequestController.scala
- app/services/ApiHubService.scala
- app/viewmodels/admin/AccessRequestEndpointGroups.scala
- app/views/admin/AccessRequestView.scala.html
- app/views/admin/AccessRequestsView.scala.html
- conf/admin.routes
- conf/messages.en
- it/connectors/ApplicationsConnectorSpec.scala
- test/controllers/actions/UserTypes.scala
- test/controllers/admin/AccessRequestControllerSpec.scala
- test/controllers/admin/AccessRequestsControllerSpec.scala
- test/services/ApiHubServiceSpec.scala
- test/viewmodels/admin/AccessRequestEndpointGroupsSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-845
> HIPP-845: Review PENDING prod API request

- app/connectors/ApplicationsConnector.scala
- app/controllers/admin/AccessRequestController.scala
- app/forms/admin/ApprovalDecisionFormProvider.scala
- app/services/ApiHubService.scala
- app/viewmodels/admin/ApprovalDecision.scala
- app/viewmodels/govuk/TextareaFluency.scala
- app/views/admin/AccessRequestRejectedSuccessView.scala.html
- app/views/admin/AccessRequestView.scala.html
- conf/messages.en
- it/connectors/ApplicationsConnectorSpec.scala
- project/plugins.sbt
- test-utils/generators/ModelGenerators.scala
- test/controllers/admin/AccessRequestControllerSpec.scala
- test/forms/admin/ApprovalDecisionFormProviderSpec.scala
- test/forms/behaviours/OptionFieldBehaviours.scala
- test/services/ApiHubServiceSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-877
> HIPP-877: Reject production access request

- app/views/AddAnApiSelectApplicationView.scala.html
- conf/messages.en
https://jira.tools.tax.service.gov.uk/browse/HIPP-891
> HIPP-891: Display the name of the API selected

- app/views/application/EnvironmentAndCredentialsView.scala.html
https://jira.tools.tax.service.gov.uk/browse/HIPP-898
> HIPP-898: Update credentials table on HIP Prod & HIP Dev tabs

- app/views/admin/AccessRequestsView.scala.html
- conf/messages.en
https://jira.tools.tax.service.gov.uk/browse/HIPP-881
The only thing to do was to add rejected reason to the access requests list page
> HIPP-881: REJECTED prod API requests

- app/viewmodels/application/ApplicationNavItems.scala
- test/viewmodels/application/ApplicationNavItemsSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-924
> HIPP-924: Hide application details links that are not in use

- app/views/RedocView.scala.html
https://jira.tools.tax.service.gov.uk/browse/HIPP-867
> HIPP-867: Enable rendering hostnames in the OAS redoc page

- app/config/FrontendAppConfig.scala
- app/controllers/ShutterController.scala
- conf/application.conf
- conf/shutter.routes
- test/controllers/ShutterControllerSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-937
> HIPP-937: Add the ability to shutter the api-hub frontend

- app/assets/stylesheets/application.css
- app/views/IndexView.scala.html
https://jira.tools.tax.service.gov.uk/browse/HIPP-723
> HIPP-723: AT fixes

- app/views/PolicyView.scala.html
- app/views/templates/Layout.scala.html
https://jira.tools.tax.service.gov.uk/browse/HIPP-958
> HIPP-958: Fix back link

- app/controllers/application/ManageTeamMembersController.scala
- app/models/application/ApplicationLenses.scala
- app/viewmodels/application/ApplicationNavItems.scala
- app/views/application/ManageTeamMembersView.scala.html
- conf/application.routes
- conf/messages.en
- project/plugins.sbt
- test/controllers/application/ManageTeamMembersControllerSpec.scala
- test/viewmodels/application/ApplicationNavItemsSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-373
> HIPP-373: Manage team members page

- app/controllers/team/ManageMyTeamsController.scala
- app/views/team/ManageMyTeamsView.scala.html
- conf/app.routes
- conf/messages.en
- conf/team.routes
- test/controllers/team/ManageMyTeamsControllerSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1041
> HIPP-1041: Manage my teams

- project/AppDependencies.scala
- project/plugins.sbt
https://jira.tools.tax.service.gov.uk/browse/HIPP-1060
> HIPP-1060: Upgrade to play-frontend-hmrc v9.0.0

- app/config/Module.scala
- app/connectors/ApplicationsConnector.scala
- app/controllers/actions/TeamAuthAction.scala
- app/controllers/team/CreateTeamMemberController.scala
- app/controllers/team/ManageTeamController.scala
- app/controllers/team/ManageTeamMembersController.scala
- app/models/requests/TeamRequest.scala
- app/models/team/Team.scala
- app/models/team/TeamLenses.scala
- app/services/ApiHubService.scala
- app/views/team/ManageTeamMembersView.scala.html
- app/views/team/ManageTeamView.scala.html
- conf/messages.en
- conf/team.routes
- it/test/connectors/ApplicationsConnectorSpec.scala
- project/plugins.sbt
- test/controllers/actions/TeamAuthActionSpec.scala
- test/controllers/team/CreateTeamMemberControllerSpec.scala
- test/controllers/team/CreateTeamNameControllerSpec.scala
- test/controllers/team/ManageTeamControllerSpec.scala
- test/controllers/team/RemoveTeamMemberControllerSpec.scala
- test/services/ApiHubServiceSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1093
> HIPP-1093: Manage [team-name]

- app/connectors/ApplicationsConnector.scala
- app/controllers/team/CreateTeamController.scala
- app/models/team/NewTeam.scala
- app/models/team/Team.scala
- app/services/ApiHubService.scala
- app/views/team/CreateTeamSuccessView.scala.html
- conf/messages.en
- conf/team.routes
- it/test/connectors/ApplicationsConnectorSpec.scala
- test/controllers/team/CreateTeamControllerSpec.scala
- test/services/ApiHubServiceSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1047
> HIPP-1047 - Team successfully created

- app/navigation/Navigator.scala
- app/viewmodels/checkAnswers/CreateTeamAddTeamMemberSummary.scala
- app/views/team/CreateTeamCheckYourAnswersView.scala.html
- test/controllers/team/CreateTeamCheckYourAnswersControllerSpec.scala
- test/controllers/team/ManageTeamMembersControllerSpec.scala
- test/navigation/NavigatorSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1083
> HIPP-1083: Navigation pages

- app/assets/javascripts/app.js
- app/views/IndexView.scala.html
- app/views/ViewUtils.scala
- app/views/admin/AccessRequestView.scala.html
- app/views/admin/AccessRequestsView.scala.html
- app/views/application/ApplicationDetailsView.scala.html
- app/views/application/EnvironmentAndCredentialsView.scala.html
- app/views/team/ManageMyTeamsView.scala.html
- test/views/ViewUtilsSpec.scala
…than utc values, and format date/time display according to gov.uk style guide
> HIPP-1136 - ensure all dates and times are displayed as local

- app/controllers/deployment/SimpleApiDeploymentController.scala
- app/models/deployment/DeploymentsRequest.scala
- app/views/deployment/SimpleApiDeploymentView.scala.html
- it/test/connectors/ApplicationsConnectorSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1155
Also add in better form validation.
> HIPP-1135: Add teams to the form

- app/models/deployment/DeploymentsRequest.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1155
teamId was in the wrong place in DeploymentsRequest
> HIPP-1155: Add teams to the form

- app/controllers/AddAnApiSelectApplicationController.scala
- test/controllers/AddAnApiSelectApplicationControllerSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-889
> HIPP-889: Rework logic behind the select application page

- app/models/api/ApiDetail.scala
- app/views/ApiDetailsView.scala.html
- conf/messages.en
- test-utils/generators/ApiDetailGenerators.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1202
> HIPP-1202: Display HOD/ Backend

- app/connectors/ApplicationsConnector.scala
- app/controllers/AddAnApiSelectApplicationController.scala
- app/controllers/ApplicationsController.scala
- app/controllers/IndexController.scala
- app/controllers/admin/ManageApplicationsController.scala
- app/models/application/Application.scala
- app/models/application/ApplicationLenses.scala
- app/models/application/Deleted.scala
- app/services/ApiHubService.scala
- app/views/admin/ManageApplicationsView.scala.html
- it/test/connectors/ApplicationsConnectorSpec.scala
- test/controllers/AddAnApiSelectApplicationControllerSpec.scala
- test/controllers/ApplicationsControllerSpec.scala
- test/controllers/IndexControllerSpec.scala
- test/controllers/admin/ManageApplicationsControllerSpec.scala
- test/services/ApiHubServiceSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1207
> HIPP-1207: View deleted applications

- app/config/Domains.scala
- app/config/Module.scala
- app/controllers/ApiDetailsController.scala
- app/models/api/ApiDetailLenses.scala
- app/views/ApiDetailsView.scala.html
- test-utils/fakes/FakeDomains.scala
- test-utils/generators/ApiDetailGenerators.scala
- test/base/OptionallyAuthenticatedSpecBase.scala
- test/base/SpecBase.scala
- test/config/DomainsSpec.scala
- test/controllers/ApiDetailsControllerSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1222
> HIPP-1222: Update domain and sub-domain values on API details page

- app/connectors/ApplicationsConnector.scala
- app/models/deployment/RedeploymentRequest.scala
- it/test/connectors/ApplicationsConnectorSpec.scala
- test/controllers/deployment/SimpleApiDeploymentControllerSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1119
> HIPP-1119: Update simple API

- app/connectors/ApplicationsConnector.scala
- app/controllers/helpers/ErrorResultBuilder.scala
- app/controllers/myapis/SimpleApiPromotionController.scala
- app/views/myapis/SimpleApiPromotionView.scala.html
- build.sbt
- conf/logback.xml
- conf/messages.en
- conf/myapis.routes
- it/test/connectors/ApplicationsConnectorSpec.scala
- test/controllers/myapis/SimpleApiPromotionControllerSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1274
> HIPP-1274: Promote to production

- app/connectors/ApplicationsConnector.scala
- app/controllers/application/ApplicationSupportController.scala
- app/controllers/application/RemoveApiController.scala
- app/controllers/helpers/ErrorResultBuilder.scala
- app/forms/YesNoFormProvider.scala
- app/models/application/ApplicationLenses.scala
- app/services/ApiHubService.scala
- app/views/application/RemoveApiConfirmationView.scala.html
- app/views/application/RemoveApiSuccessView.scala.html
- conf/application.routes
- conf/messages.en
- it/test/connectors/ApplicationsConnectorSpec.scala
- test-utils/generators/ApplicationGenerator.scala
- test/controllers/application/ApplicationSupportControllerSpec.scala
- test/controllers/application/RemoveApiControllerSpec.scala
- test/services/ApiHubServiceSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1304
> HIPP-1304: Remove API

- app/views/application/ApplicationApisView.scala.html
- conf/messages.en
https://jira.tools.tax.service.gov.uk/browse/HIPP-1302
> HIPP-1302: Remove an API link

- app/controllers/application/ApplicationDetailsController.scala
- app/controllers/helpers/ErrorResultBuilder.scala
- app/controllers/team/ManageTeamController.scala
- app/models/application/Application.scala
- app/models/application/ApplicationLenses.scala
- app/models/application/NewApplication.scala
- app/models/team/TeamLenses.scala
- app/viewmodels/application/ApplicationNavItems.scala
- app/views/application/ApplicationDetailsView.scala.html
- app/views/team/ManageTeamView.scala.html
- conf/messages.en
- conf/team.routes
- it/test/connectors/ApplicationsConnectorSpec.scala
- test-utils/generators/ApplicationGenerator.scala
- test/controllers/actions/FakeApplication.scala
- test/controllers/application/ApplicationDetailsControllerSpec.scala
- test/controllers/team/ManageTeamControllerSpec.scala
- test/viewmodels/application/ApplicationNavItemsSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1353
> HIPP-1353: Adjust the data model

- conf/application.conf
https://jira.tools.tax.service.gov.uk/browse/HIPP-1398
Update config for accessibility service
> HIPP-1398: Update accessibility service config

- build.sbt
- conf/application.conf
- conf/prod.routes
- conf/testOnlyDoNotUseInAppConf.routes
https://jira.tools.tax.service.gov.uk/browse/HIPP-1403
> HIPP-1403: Fix acceptance tests

- app/controllers/myapis/SimpleApiDeploymentController.scala
- app/models/deployment/DeploymentsRequest.scala
- app/views/myapis/SimpleApiDeploymentView.scala.html
- it/test/connectors/ApplicationsConnectorSpec.scala
- test/controllers/myapis/SimpleApiDeploymentControllerSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1402
> HIPP-1402: Add egressPrefix & prefixesToRemove

- app/connectors/ApplicationsConnector.scala
- app/controllers/myapis/SimpleApiDeploymentController.scala
- app/controllers/myapis/SimpleApiRedeploymentController.scala
- app/models/deployment/DeploymentDetails.scala
- app/services/ApiHubService.scala
- app/views/myapis/SimpleApiRedeploymentView.scala.html
- it/test/connectors/ApplicationsConnectorSpec.scala
- test/controllers/myapis/SimpleApiRedeploymentControllerSpec.scala
- test/services/ApiHubServiceSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1430
> HIPP-1430: Add egressPrefix & prefixesToRemove fields to Update form

- app/controllers/application/register/RegisterApplicationController.scala
- app/views/application/register/RegisterApplicationCheckYourAnswersView.scala.html
- app/views/application/register/RegisterApplicationSuccessView.scala.html
- conf/application.routes
- conf/messages.en
- test/controllers/application/register/RegisterApplicationCheckYourAnswersControllerSpec.scala
- test/controllers/application/register/RegisterApplicationControllerSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1452
> HIPP-1452: Submit register application

- app/controllers/team/CreateTeamCheckYourAnswersController.scala
- app/controllers/team/CreateTeamController.scala
- app/viewmodels/checkAnswers/CreateTeamAddTeamMemberSummary.scala
- app/views/application/register/RegisterApplicationSuccessView.scala.html
- app/views/application/register/RegisterApplicationTeamView.scala.html
- app/views/team/CreateTeamCheckYourAnswersView.scala.html
- app/views/team/CreateTeamNameView.scala.html
- app/views/team/CreateTeamSuccessView.scala.html
- app/views/team/ManageMyTeamsView.scala.html
- app/views/team/ManageTeamMembersView.scala.html
- app/views/team/ManageTeamView.scala.html
- test/controllers/team/CreateTeamCheckYourAnswersControllerSpec.scala
- test/controllers/team/CreateTeamControllerSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1389
> HIPP-1389: Register application acceptance tests

- app/controllers/admin/TeamMigrationController.scala
- app/views/admin/TeamMigrationView.scala.html
- test/controllers/admin/TeamMigrationControllerSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1463
> HIPP-1463: Group application by team members on migration page

- app/viewmodels/myapis/MyApisNavItems.scala
- conf/messages.en
- test/viewmodels/myapis/MyApisNavItemsSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1374
> HIPP-1374: View API as consumer

- app/assets/stylesheets/application.scss
- app/views/ApiDetailsView.scala.html
- app/views/MarkdownUtils.scala
- test/views/MarkdownUtilsSpec.scala
[Screencast from 11-09-24 12:05:42.webm](https://github.com/user-attachments/assets/dcac2e01-9780-41ea-b02e-e311244a0e65)
> HIPP-1506: Add scroll to overflow content on markdown table

- app/views/IndexView.scala.html
> HIPP-1510: Reduce spacing on the Dashboard header

- app/assets/stylesheets/application.scss
- app/controllers/myapis/produce/ProduceApiBeforeYouStartController.scala
- app/navigation/Navigator.scala
- app/pages/myapis/produce/ProduceApiBeforeYouStartPage.scala
- app/viewmodels/RelatedContentLink.scala
- app/views/components/RelatedContent.scala.html
- app/views/myapis/produce/ProduceApiBeforeYouStartView.scala.html
- conf/messages.en
- conf/myapis.routes
- test/controllers/myapis/produce/ProduceApiBeforeYouStartControllerSpec.scala
- test/navigation/NavigatorSpec.scala
- test/viewmodels/RelatedContentLinkSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-987
> HIPP-987: Produce an API

- app/controllers/admin/ConfigurationController.scala
- app/viewmodels/admin/AdminNavItems.scala
- app/views/admin/ConfigurationView.scala.html
- conf/admin.routes
- conf/messages.en
- test/controllers/admin/ConfigurationControllerSpec.scala
- test/viewmodels/admin/AdminNavItemsSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1532
> HIPP-1532: View HoD and Domain config

- app/assets/stylesheets/application.scss
- app/controllers/application/RequestProductionAccessSelectApisController.scala
- app/controllers/application/RequestProductionAccessStartController.scala
- app/forms/application/RequestProductionAccessSelectApisFormProvider.scala
- app/pages/application/accessrequest/RequestProductionAccessSelectApisPage.scala
- app/viewmodels/checkAnswers/application/accessrequest/RequestProductionAccessSelectApisSummary.scala
- app/views/application/RequestProductionAccessSelectApisView.scala.html
- conf/app.routes
- conf/application.routes
- conf/messages.en
- test-utils/generators/PageGenerators.scala
- test-utils/generators/UserAnswersEntryGenerators.scala
- test-utils/generators/UserAnswersGenerator.scala
- test/controllers/application/RequestProductionAccessSelectApisControllerSpec.scala
- test/controllers/application/RequestProductionAccessStartControllerSpec.scala
- test/forms/RequestProductionAccessSelectApisFormProviderSpec.scala
- test/pages/application/accessrequest/RequestProductionAccessSelectApisPageSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1533
> HIPP-1533 - Add RequestProductionAccessSelectApis page

- app/assets/javascripts/hubStatistics.js
- app/assets/stylesheets/application.scss
- app/connectors/ApplicationsConnector.scala
- app/controllers/admin/StatisticsController.scala
- app/models/stats/ApisInProductionStatistic.scala
- app/services/ApiHubService.scala
- app/viewmodels/admin/AdminNavItems.scala
- app/views/admin/StatisticsView.scala.html
- conf/admin.routes
- conf/messages.en
- it/test/connectors/ApplicationsConnectorSpec.scala
- jsTest/tests/hubStatistics.spec.js
- test/controllers/admin/StatisticsControllerSpec.scala
- test/services/ApiHubServiceSpec.scala
- test/viewmodels/admin/AdminNavItemsSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1542
> HIPP-1542: Display the no. of APIs deployed in prod

- app/config/Module.scala
- app/controllers/actions/CancelAccessRequestDataRetrievalAction.scala
- app/controllers/application/cancelaccessrequest/CancelAccessRequestStartController.scala
- app/pages/application/cancelaccessrequest/CancelAccessRequestApplicationPage.scala
- app/pages/application/cancelaccessrequest/CancelAccessRequestPendingPage.scala
- app/pages/application/cancelaccessrequest/CancelAccessRequestStartPage.scala
- app/repositories/CancelAccessRequestSessionRepository.scala
- conf/application.routes
- it/test/repositories/CancelAccessRequestSessionRepositorySpec.scala
- it/test/repositories/UserAnswersRepositoryBehaviours.scala
- test/base/SpecBase.scala
- test/controllers/actions/CancelAccessRequestDataRetrievalActionSpec.scala
- test/controllers/actions/FakeCancelAccessRequestDataRetrievalAction.scala
- test/controllers/application/cancelaccessrequest/CancelAccessRequestStartControllerSpec.scala
- test/utils/TestHelpers.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1545
> HIPP-1545: Start journey

- app/controllers/application/DeleteApplicationConfirmationController.scala
- app/controllers/application/accessrequest/RequestProductionAccessSelectApisController.scala
- app/views/application/DeleteApplicationConfirmationView.scala.html
- app/views/application/accessrequest/RequestProductionAccessSelectApisView.scala.html
- test/controllers/application/DeleteApplicationConfirmationControllerSpec.scala
- test/controllers/application/accessrequest/RequestProductionAccessSelectApisControllerSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1517
Problems found during testing:
- User not passed into Select APIs view
- User not passed into Delete application confirm view
This results in missing menu options.
> HIPP-1517: Fix missing user causing menu issues

- app/views/application/EnvironmentAndCredentialsView.scala.html
https://jira.tools.tax.service.gov.uk/browse/HIPP-1251
> HIPP-1251: Add ids for acceptance tests

- app/assets/stylesheets/application.scss
- app/views/AddAnApiCheckYourAnswersView.scala.html
> HIPP-1565 - fixing layout on CYA page

- app/controllers/actions/StrideAuthenticator.scala
- app/services/MetricsService.scala
- test/controllers/actions/StrideAuthenticatorSpec.scala
- test/services/MetricsServiceSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1562
> HIPP-1562: Log failed STRIDE logins where there is no email

- app/views/application/ApplicationDetailsView.scala.html
- app/views/application/accessrequest/RequestProductionAccessSuccessView.scala.html
- app/views/application/cancelaccessrequest/CancelAccessRequestSuccessView.scala.html
https://jira.tools.tax.service.gov.uk/browse/HIPP-1551
> HIPP-1551: Element ids for acceptance tests

- app/connectors/IntegrationCatalogueConnector.scala
- app/controllers/ExploreApisController.scala
- app/models/api/ApiDetail.scala
- app/models/api/ApiDetailSummary.scala
- app/services/ApiHubService.scala
- app/views/ExploreApisView.scala.html
- app/views/admin/ManageApisView.scala.html
- it/test/connectors/IntegrationCatalogueConnectorSpec.scala
- test-utils/generators/ApiDetailGenerators.scala
- test/controllers/DeepSearchApisControllerSpec.scala
- test/controllers/ExploreApisControllerSpec.scala
- test/controllers/admin/ManageApisControllerSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1603
> HIPP-1603: Use the Catalogue's API summaries endpoint

- app/views/admin/AccessRequestApprovedSuccessView.scala.html
- app/views/admin/AccessRequestRejectedSuccessView.scala.html
- app/views/components/AccessRequestPanel.scala.html
https://jira.tools.tax.service.gov.uk/browse/HIPP-1256
> HIPP-1256: Element changes for journey tests

- app/controllers/myapis/produce/ProduceApiEgressController.scala
- app/forms/myapis/produce/ProduceApiChooseEgressFormProvider.scala
- app/models/myapis/produce/ProduceApiChooseEgress.scala
- app/navigation/Navigator.scala
- test/controllers/myapis/produce/ProduceApiChooseEgressControllerSpec.scala
- test/navigation/NavigatorSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1584
Onward navigation is returning a 500 response to the user.
> HIPP-1584: Fix navigation issues

- app/connectors/ApplicationsConnector.scala
- app/controllers/application/AllScopesController.scala
- app/models/application/CredentialScopes.scala
- app/services/ApiHubService.scala
- app/viewmodels/application/ApplicationNavItems.scala
- conf/application.routes
- conf/messages.en
- it/test/connectors/ApplicationsConnectorSpec.scala
- test/controllers/application/AllScopesControllerSpec.scala
- test/services/ApiHubServiceSpec.scala
- test/viewmodels/application/ApplicationNavItemsSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1628
> HIPP-1628: Diagnostic scope view

- app/connectors/ApplicationsConnector.scala
- app/controllers/application/AllScopesController.scala
- app/services/ApiHubService.scala
- app/viewmodels/application/ApplicationNavItems.scala
- app/views/application/AllScopesView.scala.html
- conf/application.routes
- conf/messages.en
- it/test/connectors/ApplicationsConnectorSpec.scala
- test/controllers/application/AllScopesControllerSpec.scala
- test/services/ApiHubServiceSpec.scala
- test/viewmodels/application/ApplicationNavItemsSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1625
> HIPP-1625: Fix scope disparity

- app/controllers/application/ApplicationApisController.scala
- app/controllers/application/ApplicationDetailsController.scala
- app/controllers/application/accessrequest/RequestProductionAccessEndJourneyController.scala
- app/controllers/application/accessrequest/RequestProductionAccessStartController.scala
- app/controllers/helpers/ApplicationApiBuilder.scala
- app/models/api/ApiDetailLenses.scala
- app/viewmodels/application/ApplicationApi.scala
- app/views/application/ApplicationApisView.scala.html
- app/views/application/ApplicationDetailsView.scala.html
- test/controllers/application/ApplicationApisControllerSpec.scala
- test/controllers/application/ApplicationDetailsControllerSpec.scala
- test/controllers/application/accessrequest/RequestProductionAccessControllerSpec.scala
- test/controllers/application/accessrequest/RequestProductionAccessEndJourneyControllerSpec.scala
- test/controllers/application/accessrequest/RequestProductionAccessSelectApisControllerSpec.scala
- test/controllers/application/cancelaccessrequest/CancelAccessRequestEndJourneyControllerSpec.scala
- test/controllers/helpers/ApplicationApiBuilderSpec.scala
- test/viewmodels/application/ApplicationApiSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1752
> HIPP-1752: Use theoretical scopes in ApplicationApiBuilder

- app/models/application/ApplicationLenses.scala
- app/services/CurlCommandService.scala
- app/views/application/EnvironmentAndCredentialsView.scala.html
- app/views/application/EnvironmentsView.scala.html
- test/controllers/AddAnApiSelectApplicationControllerSpec.scala
- test/controllers/application/ApplicationApisControllerSpec.scala
- test/controllers/application/ApplicationDetailsControllerSpec.scala
- test/controllers/application/accessrequest/ProvideSupportingInformationControllerSpec.scala
- test/controllers/application/accessrequest/RequestProductionAccessControllerSpec.scala
- test/controllers/application/accessrequest/RequestProductionAccessEndJourneyControllerSpec.scala
- test/controllers/application/accessrequest/RequestProductionAccessStartControllerSpec.scala
- test/controllers/application/cancelaccessrequest/CancelAccessRequestEndJourneyControllerSpec.scala
- test/models/application/ApplicationLensesSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1704
> HIPP-1704: Update ApplicationLenses to be configuration driven

- app/models/application/Application.scala
- app/models/application/ApplicationLenses.scala
- app/models/application/Credential.scala
- app/models/application/EnvironmentName.scala
- app/models/application/Environments.scala
- app/views/admin/ManageApplicationsView.scala.html
- it/test/connectors/ApplicationsConnectorSpec.scala
- test-utils/generators/ApplicationGenerator.scala
- test/controllers/actions/FakeApplication.scala
- test/controllers/admin/ManageApplicationsControllerSpec.scala
- test/controllers/application/AddCredentialControllerSpec.scala
- test/controllers/application/EnvironmentsControllerSpec.scala
- test/models/application/ApplicationLensesSpec.scala
- test/services/ApiHubServiceSpec.scala
- test/services/CurlCommandServiceSpec.scala
- test/viewmodels/application/EnvironmentsViewModelSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1790
> HIPP-1790: Frontend pre-migration changes

- app/config/FrontendAppConfig.scala
- app/controllers/IndexController.scala
- app/services/ApiHubService.scala
- app/viewmodels/DashboardViewModel.scala
- app/viewmodels/govuk/ButtonFluency.scala
- app/views/IndexView.scala.html
- conf/application.conf
- conf/messages.en
- test/controllers/IndexControllerSpec.scala
- test/controllers/myapis/MyApisControllerSpec.scala
- test/services/ApiHubServiceSpec.scala
- test/viewmodels/DashboardViewModelSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1712
> HIPP-1712: Add my APIs to dashboard

- app/controllers/myapis/produce/ProduceApiCheckYourAnswersController.scala
- test/controllers/myapis/produce/ProduceApiCheckYourAnswersControllerSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1836
> HIPP-1836: Submit redirects to egress prefixes page

- test/controllers/myapis/produce/ProduceApiCheckYourAnswersControllerSpec.scala
The PR builder works but there was a compilation issue in the main pipeline.
> HIPP-1386: Try and fix pipeline compile fail

- app/controllers/ApiDetailsController.scala
- app/controllers/myapis/MyApiDetailsController.scala
- app/models/api/ApiDeploymentStatuses.scala
- test/controllers/ApiDetailsControllerSpec.scala
- test/controllers/myapis/MyApiDetailsControllerSpec.scala
- test/models/api/ApiDeploymentStatusesSpec.scala
> HIPP-1851: Order deployment statuses according to the environments order

- app/views/myapis/MyApisView.scala.html
https://jira.tools.tax.service.gov.uk/browse/HIPP-1871
> HIPP-1871: Fix links on My APIs page

- app/views/components/ApiDeployments.scala.html
- app/views/myapis/MyApiDetailsView.scala.html
- conf/messages.en
- test/controllers/ApiDetailsControllerSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1879
> HIPP-1879: Harmonise API deployment status

- app/views/application/EnvironmentsView.scala.html
https://jira.tools.tax.service.gov.uk/browse/HIPP-1882
> HIPP-1882: Environment names not consistent

- app/models/api/ApiDetail.scala
- app/models/api/ApiDetailSummary.scala
- test-utils/generators/ApiDetailGenerators.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1899
> HIPP-1899: Add apiNumber to ApiDetail

- app/controllers/OasRedocController.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1676
> HIPP-1676: Add file extension to OAS download

- app/views/AddAnApiSuccessView.scala.html
- conf/messages.en
https://jira.tools.tax.service.gov.uk/browse/HIPP-1978
> HIPP-1978: API added successfully page content change

- app/views/application/EnvironmentsViewApiTab.scala.html
- conf/messages.en
https://jira.tools.tax.service.gov.uk/browse/HIPP-1981
> HIPP-1981: Production like Environment Tab

- app/controllers/application/cancelaccessrequest/CancelAccessRequestConfirmController.scala
- app/views/application/cancelaccessrequest/CancelAccessRequestSelectApiView.scala.html
- conf/messages.en
- test/controllers/application/cancelaccessrequest/CancelAccessRequestConfirmControllerSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1988
> HIPP-1988: Which APIs do you want to cancel access requests for

- app/assets/javascripts/testApimEndpoints.js
- app/assets/stylesheets/application.scss
- app/connectors/ApimConnector.scala
- app/controllers/admin/TestApimEndpointsController.scala
- app/models/deployment/StatusResponse.scala
- app/models/deployment/SuccessfulDeploymentResponse.scala
- app/models/exception/ApimException.scala
- app/services/ApiHubService.scala
- app/viewmodels/admin/AdminNavItems.scala
- app/viewmodels/admin/ApimRequest.scala
- app/viewmodels/admin/TestApimEndpointsViewModel.scala
- app/views/admin/TestApimEndpointsView.scala.html
- conf/admin.routes
- conf/messages.en
- it/test/connectors/ApimConnectorSpec.scala
- jsTest/tests/testApimEndpoints.spec.js
- package-lock.json
- package.json
- test/controllers/admin/StatisticsControllerSpec.scala
- test/controllers/admin/TestApimEndpointsControllerSpec.scala
- test/services/ApiHubServiceSpec.scala
- test/viewmodels/admin/AdminNavItemsSpec.scala
- test/viewmodels/admin/ApimRequestSpec.scala
- test/viewmodels/admin/TestApimEndpointsViewModelSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1969
> HIPP-1969: Add admin page to send test requests to APIM APIs

- app/controllers/myapis/produce/ProduceApiCheckYourAnswersController.scala
- app/controllers/myapis/update/UpdateApiCheckYourAnswersController.scala
- app/models/deployment/DeploymentsRequest.scala
- app/models/deployment/RedeploymentRequest.scala
- it/test/connectors/ApplicationsConnectorSpec.scala
- test/controllers/myapis/produce/ProduceApiCheckYourAnswersControllerSpec.scala
- test/controllers/myapis/update/UpdateApiCheckYourAnswersControllerSpec.scala
- test/services/ApiHubServiceSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-2095
https://jira.tools.tax.service.gov.uk/browse/HIPP-2096
> HIPP-2095: Add BasePath to APIM calls

- app/assets/javascripts/exploreApisModel.js
- app/assets/javascripts/exploreApisPlatformFilters.js
- app/assets/stylesheets/application.scss
- app/config/Platforms.scala
- app/controllers/ApiDetailsController.scala
- app/models/api/ApiDetail.scala
- app/models/api/ApiDetailSummary.scala
- app/models/api/Platform.scala
- app/services/ApiHubService.scala
- app/viewmodels/myapis/MyApisNavItems.scala
- app/views/ExploreApisView.scala.html
- conf/messages.en
- conf/platforms.conf
- jsTest/tests/exploreApis.spec.js
- jsTest/tests/exploreApisPlatformFilters.spec.js
- test-utils/fakes/FakePlatforms.scala
- test-utils/generators/ApiDetailGenerators.scala
- test/controllers/ExploreApisControllerSpec.scala
- test/controllers/admin/ManageApisControllerSpec.scala
- test/services/ApiHubServiceSpec.scala
> HIPP-2119: Add counts to Explore APIs filters

- conf/hods.conf
https://jira.tools.tax.service.gov.uk/browse/HIPP-2154
> HIPP-2154: Add MDTP HoD

- app/assets/stylesheets/application.scss
- app/config/ApiStatuses.scala
- app/config/Module.scala
- app/views/apis/ApiDetailsView.scala.html
- app/views/myapis/produce/ProduceApiStatusView.scala.html
- conf/apiStatuses.conf
- conf/application.conf
- test/config/ApiStatusesSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-2162
> HIPP-2162: Update new Lifecycle statuses

- conf/apiStatuses.conf
https://jira.tools.tax.service.gov.uk/browse/HIPP-2208
> HIPP-2208: Rename API statuses

- app/config/FrontendAppConfig.scala
- app/config/V2Features.scala
- app/viewmodels/DashboardViewModel.scala
- app/viewmodels/team/ManageTeamNavItems.scala
- app/views/myapis/produce/ProduceApiChooseTeamView.scala.html
- app/views/team/ManageTeamEgressesView.scala.html
- app/views/team/ManageTeamView.scala.html
- conf/application.conf
- test/config/V2FeaturesSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-2205
> HIPP-2205: App config to control which teams are V2 enabled
